api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Security/Registration/UI/Http/Resource/']

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Security\Registration\:
        resource: './'
        exclude:
            - './Domain/'
            - './Infrastructure/Symfony/DependencyInjection/'
            - './UI/Resources/'

    App\Security\Registration\Domain\UserRepositoryInterface: '@App\Security\Registration\Infrastructure\PDO\UserRepository'
