twig:
    paths:
        '%kernel.project_dir%/src/Shared/UI/Resources/templates': 'shared'

parameters:
    shared.database:
        dsn: '%env(DB_DSN)%'
        username: '%env(DB_USERNAME)%'
        password: '%env(DB_PASSWORD)%'
    shared.migrations.path: '%kernel.project_dir%/database/migrations'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $dbParameters: '%shared.database%'
            $migrationsPath: '%shared.migrations.path%'

    App\Shared\:
        resource: '../../../'
        exclude:
            - '../../../Infrastructure/Symfony/_config/'
            - '../../../Infrastructure/Symfony/DependencyInjection/'
            - '../../../UI/Resources/'

    Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler:
        arguments:
            - '@Redis'

    Redis:
        class: \Redis
        calls:
            - connect:
                  - '%env(REDIS_HOST)%'
                  - '%env(REDIS_PORT)%'
