services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Shared\:
        resource: '../../../'
        exclude:
            - '../../../Infrastructure/Symfony/_config/'
            - '../../../Infrastructure/Symfony/DependencyInjection/'

    Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler:
        arguments:
            - '@Redis'

    Redis:
        class: \Redis
        calls:
            - connect:
                  - '%env(REDIS_HOST)%'
                  - '%env(REDIS_PORT)%'
